### ISSUE TITLE
Pulse cannot be armed due to tripped sensor

### ISSUE THREAD

**Issue by elight** [homeassistant-projects/hass-adtpulse#49]
Checked the Pulse app. No tripped sensor. My HA log shows this:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:39:36 AM (5 occurrences)
Last logged: 12:42:33 AM

[139656657604544] Pulse system cannot be armed due to opened/tripped zone - use force arm
[139656485151040] Pulse system cannot be armed due to opened/tripped zone - use force arm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/adtpulse/alarm_control_panel.py", line 190, in async_alarm_arm_home
    await self._perform_alarm_action(
  File "/config/custom_components/adtpulse/alarm_control_panel.py", line 153, in _perform_alarm_action
    await self._check_if_system_armable(action)
  File "/config/custom_components/adtpulse/alarm_control_panel.py", line 186, in _check_if_system_armable
    raise HomeAssistantError(ARM_ERROR_MESSAGE)
homeassistant.exceptions.HomeAssistantError: Pulse system cannot be armed due to opened/tripped zone - use force arm
```

**Comment by EVWorth** [comment]
@elight I know this is over a year old, but Ive updated this to support HA 2025.8.0. can you update the integration and test again?

**Comment by EVWorth** [comment]
if so, please re-open here: https://github.com/EVWorth/hass-adtpulse
